In [297]:
import numpy as np
import pandas as pd

In [298]:
from surprise import SVD, KNNBaseline, Dataset, Reader
from surprise.model_selection import train_test_split
from surprise import accuracy
from surprise.model_selection import cross_validate

In [299]:
import time

In [300]:
path = "interactions_data/"

In [301]:
df_movies = pd.read_csv(path + 'movies_data.csv')
df_interactions = pd.read_csv(path + 'interactions_data.csv')

In [302]:
df_movies.rename(columns={'id': 'movie_id', 'title': 'title', 'genres': 'genres'}, inplace=True)

In [303]:
df_movies.head()

,movie_id,title,description,genres,actors,directors
0,37702,Forbidden City Cop,An imperial agent gets ridiculed for his vario...,"Adventure, Action, Comedy","Stephen Chow, Carina Lau, Carman Lee Yeuk-Tung...",Vincent Kok Tak-Chiu
1,1290821,Shelter,A man living in self-imposed exile on a remote...,"Action, Thriller, Crime","Jason Statham, Bodhi Rae Breathnach, Bill Nigh...",Ric Roman Waugh
2,1171145,Crime 101,When an elusive thief whose high-stakes heists...,"Thriller, Crime","Chris Hemsworth, Mark Ruffalo, Halle Berry, Ba...",Bart Layton
3,1198994,Send Help,Two colleagues become stranded on a deserted i...,"Horror, Comedy, Thriller","Rachel McAdams, Dylan O'Brien, Edyll Ismail, D...",Sam Raimi
4,840464,Greenland 2: Migration,Having found the safety of the Greenland bunke...,"Adventure, Thriller, Science Fiction","Gerard Butler, Morena Baccarin, Roman Griffin ...",Ric Roman Waugh

In [304]:
df_interactions.head()

,user_id,movie_id,rating,max_progress_percent,favourite,in_watchlist,view_count,last_watched_at
0,10,69492,NaN,85,0,1,3,2025-12-18 01:56:05.017054
1,10,28932,NaN,80,0,0,1,2026-02-02 01:56:05.032371
2,10,372754,NaN,85,0,1,2,2025-12-10 01:56:05.042977
3,10,210479,NaN,82,0,0,6,2025-10-20 01:56:05.053147
4,10,16071,NaN,80,0,0,7,2025-10-30 01:56:05.064748

In [305]:
def calculate_base_score(row, weights):
    v_progress = row['max_progress_percent'] / 100
    v_rating = row['rating'] / 5.0 if pd.notnull(row['rating']) else None
    v_fav = float(row['favourite'])
    v_watchlist = float(row['in_watchlist'])
    v_view_count = np.log(max(row['view_count'], 1)) / np.log(10)

    # Tính điểm theo từng thành phần hợp lệ
    numerator = (
        weights['progress'] * v_progress
        + weights['favourite'] * v_fav
        + weights['watchlist'] * v_watchlist
        + weights['view_count'] * v_view_count
    )
    denominator = (
        weights['progress']
        + weights['favourite']
        + weights['watchlist']
        + weights['view_count']
    )

    # Chỉ cộng rating khi có dữ liệu
    if v_rating is not None:
        numerator += weights['rating'] * v_rating
        denominator += weights['rating']

    return numerator / denominator * 10

In [306]:
weights = {
    'progress': 3.0,
    'rating': 4.1,
    'favourite': 4.5,
    'watchlist': 2.0,
    'view_count': 1.1
}

df_interactions['base_score'] = df_interactions.apply(calculate_base_score, axis=1, weights=weights)

In [307]:
df_interactions

,user_id,movie_id,rating,max_progress_percent,favourite,in_watchlist,view_count,last_watched_at,base_score
0,10,69492,NaN,85,0,1,3,2025-12-18 01:56:05.017054,4.787579
1,10,28932,NaN,80,0,0,1,2026-02-02 01:56:05.032371,2.264151
2,10,372754,NaN,85,0,1,2,2025-12-10 01:56:05.042977,4.604842
3,10,210479,NaN,82,0,0,6,2025-10-20 01:56:05.053147,3.128270
4,10,16071,NaN,80,0,0,7,2025-10-30 01:56:05.064748,3.141139
...,...,...,...,...,...,...,...,...,...
27011,500,15276,5.0,97,1,0,4,2025-12-06 01:59:01.806758,8.280453
27012,500,736545,5.0,81,1,1,3,2026-03-08 01:59:01.818289,9.220975
27013,500,11297,4.0,92,0,0,2,2025-10-01 01:59:01.826666,4.334104
27014,500,146724,5.0,90,1,0,3,2025-10-04 01:59:01.838193,8.044104
27015,500,425503,5.0,93,1,0,1,2025-10-07 01:59:01.846974,7.748299

In [308]:
from collections import Counter

In [309]:
# Algorithm 1: Phân loại thể loại yêu thích và không thích của người dùng

def get_user_genres_preferences(user_id, df_interaction, df_items):
  # Get movieId which user rated
  user_ratings = df_interactions[df_interaction['user_id'] == user_id]

  # Count genre
  genre_counts = Counter()
  for m_id in user_ratings['movie_id']:
    # Get string genres of movie ("Action|Adventure")
    genre_str = df_items.loc[df_items['movie_id'] == m_id, 'genres'].values[0]
    if pd.isna(genre_str): continue
    for genre in genre_str.split(', '):
      genre_counts[genre] += 1

  # Get all genre
  all_genres = set()
  df_items['genres'].str.split(', ').apply(lambda x: all_genres.update(x) if isinstance(x, list) else None)

  # Sort asc
  sorted_genres = sorted(list(all_genres), key=lambda x: genre_counts.get(x, 0), reverse=True)

  # Find mid-point
  mid_point = len(sorted_genres) // 2
  fav_genres = sorted_genres[:mid_point]
  unfav_genres = sorted_genres[mid_point:]

  return fav_genres, unfav_genres

In [310]:
# Algorithm 2: Kiểm tra tính liên quan (Relevance) dựa trên Genre
def is_movie_relevant(movie_id, df_movies, fav_genres, unfav_genres):
    res = df_movies.loc[df_movies['movie_id'] == movie_id, 'genres'].values
    if len(res) == 0 or pd.isna(res[0]): return False

    movie_genres = [g.strip() for g in res[0].split(', ')]
    # Score = (Số genre thích) - (Số genre ghét)
    score = sum(1 for g in movie_genres if g in fav_genres) - \
            sum(1 for g in movie_genres if g in unfav_genres)
    return score > 0

In [317]:
# Algorithm 4: Tính các chỉ số Precision@K, Recall@K, F1 score
def calculate_metrics_at_k(predictions, df_interaction, df_movies, k):
  user_est_true = {}
  for uid, iid, true_r, est, _ in predictions:
    if uid not in user_est_true:
      user_est_true[uid] = []
    user_est_true[uid].append((iid, est))

  precisions = []
  recalls = []

  for uid, user_ratings in user_est_true.items():
    # Lấy gu của user
    fav, unfav= get_user_genres_preferences(uid, df_interaction, df_movies)

    # Sắp xếp dự đoán theo điểm 'est' cao nhất
    user_ratings.sort(key=lambda x: x[1], reverse=True)
    top_k = user_ratings[:k]

    # Tính TP (True Positives)
    n_rel_and_rec_k = sum(1 for (iid, est) in top_k if is_movie_relevant(iid, df_movies, fav, unfav))

    # Tính tổng số phim relevant thực tế có trong tập test của user
    n_rel = sum(1 for (iid, est) in user_ratings if is_movie_relevant(iid, df_movies, fav, unfav))

    # Tính precision and recall cho user
    precisions.append(n_rel_and_rec_k / k)
    recalls.append(n_rel_and_rec_k / n_rel if n_rel != 0 else 0)

  # Lấy avg
  avg_prec = np.mean(precisions)
  avg_rec = np.mean(recalls)

  f1 = (2 * avg_prec * avg_rec) / (avg_rec + avg_prec) if (avg_rec + avg_prec) >0 else 0

  return avg_prec, avg_rec, f1

In [318]:
from surprise import SVD, KNNBaseline, CoClustering, NMF, SlopeOne, BaselineOnly

In [319]:
# Danh sách các thuật toán
algorithms = [
    SVD(),
    CoClustering(),
    NMF(),
    SlopeOne(),
    KNNBaseline(),
    BaselineOnly()
]

In [320]:
# Chia dữ liệu Trainning và test, tỉ lệ 75/25
reader = Reader(rating_scale=(0, 10))

data = Dataset.load_from_df(df_interactions[['user_id', 'movie_id', 'base_score']], reader)

trainset, testset = train_test_split(data, test_size=0.25)

In [321]:
# Huấn luyện, dự đoán và đo thời gian
results_table = []

for algorithm in algorithms:
  algo_name = algorithm.__class__.__name__

  start_time = time.time()

  # Train
  algorithm.fit(trainset)

  # Predict
  predictions = algorithm.test(testset)

  #Time
  eval_time = time.time() - start_time


  # Tinh RMSE va MAE
  rmse_val = accuracy.rmse(predictions, verbose=False)
  mae_val = accuracy.mae(predictions, verbose=False)

  # Tinh Precision, recall, f1
  prec, rec, f1 = calculate_metrics_at_k(predictions, df_interactions, df_movies, k = 15)

  results_table.append([algo_name, rmse_val, mae_val, prec, rec, f1, eval_time])
  print(f"{algo_name:<15} | {rmse_val:<8.4f} | {mae_val:<8.4f} | {prec:<10.4f} | {rec:<8.4f} | {f1:<8.4f} | {eval_time:<8.4f}")

SVD             | 1.9575   | 1.4692   | 0.7344     | 0.9426   | 0.8256   | 0.4175
CoClustering    | 2.6208   | 2.0696   | 0.7347     | 0.9429   | 0.8259   | 0.9982
NMF             | 2.4912   | 1.9173   | 0.7359     | 0.9440   | 0.8271   | 0.7932
SlopeOne        | 2.2904   | 1.7189   | 0.7360     | 0.9442   | 0.8272   | 0.9236
Estimating biases using als...
Computing the msd similarity matrix...
Done computing similarity matrix.
KNNBaseline     | 2.1613   | 1.6407   | 0.7351     | 0.9432   | 0.8262   | 0.0963
Estimating biases using als...
BaselineOnly    | 1.9753   | 1.4986   | 0.7337     | 0.9419   | 0.8249   | 0.0546

In [323]:

# Xuất ra DataFrame 
df_final_results = pd.DataFrame(results_table, columns=['Algorithms', 'RMSE', 'MAE', 'Precision', 'Recall', 'F1 Score', 'Time'])
df_final_results

     Algorithms      RMSE       MAE  Precision    Recall  F1 Score      Time
0           SVD  1.957547  1.469183   0.734420  0.942620  0.825596  0.417533
1  CoClustering  2.620812  2.069606   0.734691  0.942918  0.825882  0.998192
2           NMF  2.491200  1.917316   0.735913  0.943985  0.827063  0.793185
3      SlopeOne  2.290428  1.718929   0.736049  0.944193  0.827229  0.923576
4   KNNBaseline  2.161273  1.640750   0.735098  0.943185  0.826242  0.096289
5  BaselineOnly  1.975302  1.498595   0.733741  0.941902  0.824892  0.054614

In [324]:
print(predictions)

[Prediction(uid=181, iid=139582, r_ui=7.496331866677336, est=5.209874434956224, details={'was_impossible': False}), Prediction(uid=459, iid=194662, r_ui=8.878321765462843, est=5.399477461631739, details={'was_impossible': False}), Prediction(uid=445, iid=515916, r_ui=1.3867924528301887, est=2.1600961836508907, details={'was_impossible': False}), Prediction(uid=303, iid=421, r_ui=8.961495908633427, est=5.847541362440747, details={'was_impossible': False}), Prediction(uid=92, iid=504562, r_ui=3.187610381858133, est=2.8989962517067185, details={'was_impossible': False}), Prediction(uid=268, iid=554776, r_ui=3.4560367789539037, est=3.2838110742508277, details={'was_impossible': False}), Prediction(uid=106, iid=1248226, r_ui=2.9172320664724136, est=3.0142310600734867, details={'was_impossible': False}), Prediction(uid=423, iid=45657, r_ui=4.717573728021517, est=6.184191893550116, details={'was_impossible': False}), Prediction(uid=131, iid=792237, r_ui=2.1415094339622645, est=2.395452114094364, details={'was_impossible': False}), Prediction(uid=40, iid=934201, r_ui=7.312925170068027, est=5.734981423897444, details={'was_impossible': False}), Prediction(uid=456, iid=552688, r_ui=0.25471698113207547, est=3.1821812692671623, details={'was_impossible': False}), Prediction(uid=185, iid=53525, r_ui=2.3207547169811322, est=3.204900020702719, details={'was_impossible': False}), Prediction(uid=325, iid=1143440, r_ui=4.027981629408421, est=4.94935118260922, details={'was_impossible': False}), Prediction(uid=210, iid=8009, r_ui=0.14150943396226418, est=6.265618393185343, details={'was_impossible': False}), Prediction(uid=418, iid=28366, r_ui=1.1088435374149659, est=4.87000107948293, details={'was_impossible': False}), Prediction(uid=167, iid=1248226, r_ui=3.0705975284826685, est=3.2173602452605774, details={'was_impossible': False}), Prediction(uid=163, iid=14257, r_ui=3.5373658905808325, est=3.498303130464369, details={'was_impossible': False}), Prediction(uid=66, iid=14160, r_ui=7.851881626163783, est=6.065631190332879, details={'was_impossible': False}), Prediction(uid=465, iid=35854, r_ui=0.22641509433962262, est=1.9843067836772477, details={'was_impossible': False}), Prediction(uid=39, iid=10147, r_ui=7.805033323599413, est=5.448838015827842, details={'was_impossible': False}), Prediction(uid=461, iid=34016, r_ui=2.6331443351229993, est=2.9202182625780218, details={'was_impossible': False}), Prediction(uid=280, iid=129171, r_ui=4.252471425326789, est=5.974449248994013, details={'was_impossible': False}), Prediction(uid=229, iid=68883, r_ui=0.8490566037735848, est=2.5729473306826276, details={'was_impossible': False}), Prediction(uid=316, iid=661671, r_ui=0.7358490566037736, est=5.730946082781197, details={'was_impossible': False}), Prediction(uid=15, iid=1433087, r_ui=5.593969664165738, est=3.4514477738324407, details={'was_impossible': False}), Prediction(uid=64, iid=814889, r_ui=2.646069226595876, est=2.12972970772157, details={'was_impossible': False}), Prediction(uid=203, iid=2246, r_ui=3.1411394754864936, est=3.3220979061479303, details={'was_impossible': False}), Prediction(uid=490, iid=376581, r_ui=2.650943396226415, est=2.5770217410901006, details={'was_impossible': False}), Prediction(uid=294, iid=14765, r_ui=0.9056603773584905, est=1.7942847209518908, details={'was_impossible': False}), Prediction(uid=291, iid=8698, r_ui=2.8158805473505932, est=3.4229931154660846, details={'was_impossible': False}), Prediction(uid=189, iid=372921, r_ui=7.589092772395923, est=4.936569255139299, details={'was_impossible': False}), Prediction(uid=161, iid=791568, r_ui=5.467892807001894, est=2.8546131206954795, details={'was_impossible': False}), Prediction(uid=99, iid=137333, r_ui=9.5910659896392, est=5.69140013572525, details={'was_impossible': False}), Prediction(uid=54, iid=1552, r_ui=0.990566037735849, est=4.381403378061151, details={'was_impossible': False}), Prediction(uid=403, iid=713539, r_ui=3.087043387227131, est=3.3073511689177533, details={'was_impossible': False}), Prediction(uid=374, iid=784696, r_ui=4.588322027341245, est=4.870628852026583, details={'was_impossible': False}), Prediction(uid=354, iid=187826, r_ui=7.170068027210884, est=5.332099704152937, details={'was_impossible': False}), Prediction(uid=323, iid=20323, r_ui=5.395856456618569, est=3.5176807167909145, details={'was_impossible': False}), Prediction(uid=440, iid=2503, r_ui=3.5409424393312627, est=2.944345891279573, details={'was_impossible': False}), Prediction(uid=492, iid=175574, r_ui=2.660377358490566, est=3.3506693314758276, details={'was_impossible': False}), Prediction(uid=442, iid=551964, r_ui=5.442327362990208, est=3.641147627430511, details={'was_impossible': False}), Prediction(uid=10, iid=16071, r_ui=3.1411394754864936, est=3.3993792000214, details={'was_impossible': False}), Prediction(uid=402, iid=10249, r_ui=1.5374149659863945, est=5.141549418104679, details={'was_impossible': False}), Prediction(uid=339, iid=518495, r_ui=3.3675545698261153, est=3.7669001108091145, details={'was_impossible': False}), Prediction(uid=92, iid=1198994, r_ui=3.6788753245430965, est=3.528537773981271, details={'was_impossible': False}), Prediction(uid=395, iid=458005, r_ui=2.788647523983026, est=2.5898769738504073, details={'was_impossible': False}), Prediction(uid=181, iid=7735, r_ui=5.17918298346336, est=5.162184251414344, details={'was_impossible': False}), Prediction(uid=63, iid=384527, r_ui=8.207369646388862, est=5.625413873789457, details={'was_impossible': False}), Prediction(uid=492, iid=251, r_ui=4.815880547350593, est=3.3423521927658695, details={'was_impossible': False}), Prediction(uid=146, iid=602661, r_ui=3.341760368359206, est=3.1259939102812235, details={'was_impossible': False}), Prediction(uid=57, iid=51017, r_ui=1.3018867924528306, est=3.090874452102439, details={'was_impossible': False}), Prediction(uid=220, iid=39123, r_ui=7.544988432129509, est=4.748200187386854, details={'was_impossible': False}), Prediction(uid=322, iid=305470, r_ui=3.2970126228222907, est=3.071992148056352, details={'was_impossible': False}), Prediction(uid=421, iid=535167, r_ui=3.1272013020675744, est=3.211166728373228, details={'was_impossible': False}), Prediction(uid=279, iid=34314, r_ui=7.831473462898475, est=5.3854423230186015, details={'was_impossible': False}), Prediction(uid=375, iid=300681, r_ui=8.208140391443543, est=5.311967109572784, details={'was_impossible': False}), Prediction(uid=13, iid=57157, r_ui=3.0068027210884356, est=2.174519806595019, details={'was_impossible': False}), Prediction(uid=11, iid=94182, r_ui=3.241477712662272, est=2.9059365788267644, details={'was_impossible': False}), Prediction(uid=449, iid=467905, r_ui=9.13934243550451, est=5.482036462642687, details={'was_impossible': False}), Prediction(uid=247, iid=324857, r_ui=1.1320754716981134, est=2.3481904983995676, details={'was_impossible': False}), Prediction(uid=424, iid=40807, r_ui=7.385011139742862, est=5.800174590847702, details={'was_impossible': False}), Prediction(uid=136, iid=403310, r_ui=7.319727891156463, est=4.848257873498818, details={'was_impossible': False}), Prediction(uid=255, iid=585261, r_ui=3.295805020538523, est=2.4667461607521064, details={'was_impossible': False}), Prediction(uid=405, iid=66160, r_ui=5.106099575117012, est=5.25334358174949, details={'was_impossible': False}), Prediction(uid=26, iid=265712, r_ui=2.4056603773584904, est=3.313641053317898, details={'was_impossible': False}), Prediction(uid=40, iid=28178, r_ui=7.922426105729256, est=5.2195766493121, details={'was_impossible': False}), Prediction(uid=58, iid=733064, r_ui=1.1603773584905661, est=3.2763624662497692, details={'was_impossible': False}), Prediction(uid=136, iid=143665, r_ui=7.108843537414966, est=4.775031938913343, details={'was_impossible': False}), Prediction(uid=417, iid=1279788, r_ui=3.650573437750644, est=3.363399560476234, details={'was_impossible': False}), Prediction(uid=216, iid=58224, r_ui=1.2169811320754718, est=3.385389975685964, details={'was_impossible': False}), Prediction(uid=261, iid=320288, r_ui=0.39622641509433965, est=5.476603828103733, details={'was_impossible': False}), Prediction(uid=269, iid=11088, r_ui=4.604842448330547, est=3.209126341862658, details={'was_impossible': False}), Prediction(uid=216, iid=11372, r_ui=2.576540561538094, est=3.385389975685964, details={'was_impossible': False}), Prediction(uid=304, iid=211672, r_ui=5.15930849506568, est=3.408275873455783, details={'was_impossible': False}), Prediction(uid=221, iid=2898, r_ui=3.3291198158203974, est=3.2414723132669523, details={'was_impossible': False}), Prediction(uid=25, iid=10997, r_ui=0.7075471698113207, est=3.1919212145163414, details={'was_impossible': False}), Prediction(uid=229, iid=274790, r_ui=0.45283018867924524, est=2.4158265498332536, details={'was_impossible': False}), Prediction(uid=327, iid=660335, r_ui=3.1411394754864936, est=3.4190855006555676, details={'was_impossible': False}), Prediction(uid=165, iid=13161, r_ui=1.1037735849056605, est=2.8391050576757095, details={'was_impossible': False}), Prediction(uid=129, iid=309302, r_ui=0.45283018867924524, est=1.5055909402909364, details={'was_impossible': False}), Prediction(uid=311, iid=18785, r_ui=3.767357533670885, est=2.77965706628591, details={'was_impossible': False}), Prediction(uid=315, iid=454293, r_ui=7.364602976477556, est=5.721890814102664, details={'was_impossible': False}), Prediction(uid=361, iid=591538, r_ui=0.990566037735849, est=2.2270958580188602, details={'was_impossible': False}), Prediction(uid=183, iid=391, r_ui=3.298081486247178, est=3.449508293479095, details={'was_impossible': False}), Prediction(uid=211, iid=71676, r_ui=3.370062255151659, est=3.3123850327632836, details={'was_impossible': False}), Prediction(uid=476, iid=428288, r_ui=5.102704721480775, est=3.3015067223462045, details={'was_impossible': False}), Prediction(uid=360, iid=20304, r_ui=2.933962264150943, est=3.5723183906090155, details={'was_impossible': False}), Prediction(uid=115, iid=2212, r_ui=2.831257542670169, est=3.6617587672801966, details={'was_impossible': False}), Prediction(uid=255, iid=1289936, r_ui=0.990566037735849, est=2.9212507198164968, details={'was_impossible': False}), Prediction(uid=183, iid=227348, r_ui=3.1565720522849134, est=3.2671303119784145, details={'was_impossible': False}), Prediction(uid=495, iid=169881, r_ui=0.8773584905660377, est=4.951541823129501, details={'was_impossible': False}), Prediction(uid=172, iid=11587, r_ui=0.14150943396226418, est=3.2666601321124475, details={'was_impossible': False}), Prediction(uid=304, iid=316000, r_ui=3.298081486247178, est=3.460102952501087, details={'was_impossible': False}), Prediction(uid=45, iid=71668, r_ui=8.248956717974155, est=4.874913967574009, details={'was_impossible': False}), Prediction(uid=496, iid=69310, r_ui=3.114276410594697, est=3.397692773152366, details={'was_impossible': False}), Prediction(uid=314, iid=1498, r_ui=2.7309748869732346, est=1.44181187313878, details={'was_impossible': False}), Prediction(uid=188, iid=2976, r_ui=4.913876861014379, est=4.8339408887627044, details={'was_impossible': False}), Prediction(uid=148, iid=253376, r_ui=6.721088435374149, est=4.141753588940491, details={'was_impossible': False}), Prediction(uid=331, iid=37834, r_ui=2.859559429462622, est=3.5547572138062233, details={'was_impossible': False}), Prediction(uid=185, iid=44731, r_ui=2.8878613162550746, est=3.221417449540923, details={'was_impossible': False}), Prediction(uid=240, iid=55784, r_ui=2.3679245283018866, est=5.654852997937225, details={'was_impossible': False}), Prediction(uid=10, iid=1807, r_ui=3.7390556468784313, est=3.3993792000214, details={'was_impossible': False}), Prediction(uid=157, iid=550353, r_ui=1.330188679245283, est=2.4875812020467674, details={'was_impossible': False}), Prediction(uid=228, iid=892222, r_ui=3.018867924528302, est=2.3277231589324106, details={'was_impossible': False}), Prediction(uid=12, iid=10590, r_ui=3.169441362278946, est=3.204489659766721, details={'was_impossible': False}), Prediction(uid=449, iid=551804, r_ui=4.872289789429088, est=5.4351631637249005, details={'was_impossible': False}), Prediction(uid=115, iid=300681, r_ui=3.565667777373285, est=3.364677421723859, details={'was_impossible': False}), Prediction(uid=304, iid=1807, r_ui=3.565667777373285, est=3.316390900424163, details={'was_impossible': False}), Prediction(uid=24, iid=1052558, r_ui=7.170838772265564, est=5.45185042776022, details={'was_impossible': False}), Prediction(uid=368, iid=309304, r_ui=2.9172320664724136, est=3.1517583678541734, details={'was_impossible': False}), Prediction(uid=221, iid=1254754, r_ui=3.298081486247178, est=3.559322519691456, details={'was_impossible': False}), Prediction(uid=474, iid=1144107, r_ui=3.286225458199187, est=3.148896103352656, details={'was_impossible': False}), Prediction(uid=224, iid=251385, r_ui=3.371131118576545, est=3.524063020083482, details={'was_impossible': False}), Prediction(uid=220, iid=1047041, r_ui=8.046848302564367, est=5.377776210728994, details={'was_impossible': False}), Prediction(uid=36, iid=41357, r_ui=2.020408163265306, est=2.4302937232352195, details={'was_impossible': False}), Prediction(uid=82, iid=103731, r_ui=5.354685259832083, est=3.3149105722386363, details={'was_impossible': False}), Prediction(uid=363, iid=18501, r_ui=2.831257542670169, est=3.255663229481365, details={'was_impossible': False}), Prediction(uid=63, iid=235, r_ui=7.833990731579597, est=5.76079178980365, details={'was_impossible': False}), Prediction(uid=178, iid=9354, r_ui=3.0461009478958685, est=2.9872711990743257, details={'was_impossible': False}), Prediction(uid=39, iid=59053, r_ui=9.81358256831429, est=5.670063485472761, details={'was_impossible': False}), Prediction(uid=470, iid=1198984, r_ui=5.505713595708257, est=5.574380606361218, details={'was_impossible': False}), Prediction(uid=93, iid=113, r_ui=0.33962264150943394, est=2.5488659517983487, details={'was_impossible': False}), Prediction(uid=145, iid=565426, r_ui=3.275396857273216, est=2.0349536848136, details={'was_impossible': False}), Prediction(uid=423, iid=58244, r_ui=7.363832231422877, est=5.7847577893115965, details={'was_impossible': False}), Prediction(uid=363, iid=417859, r_ui=3.3958564566185685, est=3.013863033652191, details={'was_impossible': False}), Prediction(uid=284, iid=4961, r_ui=1.1037735849056605, est=4.515316430241092, details={'was_impossible': False}), Prediction(uid=197, iid=451500, r_ui=4.901247197409272, est=6.045779971320223, details={'was_impossible': False}), Prediction(uid=309, iid=3021, r_ui=3.5975462129161677, est=3.4338693705134524, details={'was_impossible': False}), Prediction(uid=374, iid=124905, r_ui=8.83904692904159, est=4.789674284123619, details={'was_impossible': False}), Prediction(uid=411, iid=535167, r_ui=3.0705975284826685, est=3.040976180036743, details={'was_impossible': False}), Prediction(uid=88, iid=98566, r_ui=0.5943396226415094, est=3.6227020105376697, details={'was_impossible': False}), Prediction(uid=301, iid=1278101, r_ui=8.470158500156721, est=5.102806529193553, details={'was_impossible': False}), Prediction(uid=360, iid=39857, r_ui=2.9290880945204045, est=3.592971351943456, details={'was_impossible': False}), Prediction(uid=209, iid=3110, r_ui=3.0705975284826685, est=3.489998524653316, details={'was_impossible': False}), Prediction(uid=455, iid=278774, r_ui=8.362856452851114, est=5.845717748192008, details={'was_impossible': False}), Prediction(uid=343, iid=1169789, r_ui=2.660377358490566, est=2.9785046606481167, details={'was_impossible': False}), Prediction(uid=335, iid=519176, r_ui=4.761134016850082, est=5.175935125843931, details={'was_impossible': False}), Prediction(uid=231, iid=1824, r_ui=2.509433962264151, est=3.061246666947532, details={'was_impossible': False}), Prediction(uid=412, iid=1071585, r_ui=0.9339622641509435, est=4.7006990256392225, details={'was_impossible': False}), Prediction(uid=436, iid=181009, r_ui=2.209684896661093, est=2.476132890279538, details={'was_impossible': False}), Prediction(uid=60, iid=39469, r_ui=7.159750598769815, est=4.997669869636523, details={'was_impossible': False}), Prediction(uid=272, iid=152748, r_ui=2.627391830245414, est=2.4683133259201973, details={'was_impossible': False}), Prediction(uid=136, iid=866462, r_ui=7.872289789429088, est=4.533189720143404, details={'was_impossible': False}), Prediction(uid=184, iid=168259, r_ui=0.6226415094339623, est=1.9395897263337123, details={'was_impossible': False}), Prediction(uid=41, iid=329724, r_ui=7.629909098926536, est=5.255723709189376, details={'was_impossible': False}), Prediction(uid=30, iid=15999, r_ui=4.681813598952897, est=4.797758540823605, details={'was_impossible': False}), Prediction(uid=213, iid=35056, r_ui=7.84327064218754, est=4.8482309938944494, details={'was_impossible': False}), Prediction(uid=425, iid=8916, r_ui=7.626621085190735, est=5.595714107673538, details={'was_impossible': False}), Prediction(uid=485, iid=353491, r_ui=2.689748108707905, est=3.430890596069031, details={'was_impossible': False}), Prediction(uid=494, iid=754, r_ui=0.9339622641509435, est=5.236844654905345, details={'was_impossible': False}), Prediction(uid=195, iid=2666, r_ui=3.1904761904761902, est=2.477691421523199, details={'was_impossible': False}), Prediction(uid=272, iid=459992, r_ui=2.7641509433962264, est=2.6207799303616204, details={'was_impossible': False}), Prediction(uid=466, iid=353070, r_ui=3.2013197978218284, est=3.44958237224961, details={'was_impossible': False}), Prediction(uid=14, iid=1156594, r_ui=2.056603773584906, est=3.388339892099376, details={'was_impossible': False}), Prediction(uid=408, iid=416249, r_ui=3.3958564566185685, est=3.179596343132497, details={'was_impossible': False}), Prediction(uid=39, iid=991494, r_ui=8.448979591836736, est=5.5295977489066885, details={'was_impossible': False}), Prediction(uid=458, iid=384018, r_ui=8.92594081308189, est=6.412432881592639, details={'was_impossible': False}), Prediction(uid=258, iid=514710, r_ui=5.087043387227132, est=3.070154389991383, details={'was_impossible': False}), Prediction(uid=338, iid=10843, r_ui=4.482993197278912, est=5.740037385102434, details={'was_impossible': False}), Prediction(uid=76, iid=1158915, r_ui=0.5660377358490567, est=5.533090805639245, details={'was_impossible': False}), Prediction(uid=162, iid=4942, r_ui=4.461894192467625, est=2.403686830069376, details={'was_impossible': False}), Prediction(uid=284, iid=15724, r_ui=7.2124258438508555, est=5.154863332449671, details={'was_impossible': False}), Prediction(uid=258, iid=1301988, r_ui=3.0304396136422245, est=2.497652049804355, details={'was_impossible': False}), Prediction(uid=311, iid=531219, r_ui=2.3773584905660377, est=3.1146481373234027, details={'was_impossible': False}), Prediction(uid=52, iid=161715, r_ui=2.990566037735849, est=3.294471925188335, details={'was_impossible': False}), Prediction(uid=294, iid=40038, r_ui=1.0188679245283019, est=2.0656054561246324, details={'was_impossible': False}), Prediction(uid=468, iid=784696, r_ui=3.114276410594697, est=3.099805054959355, details={'was_impossible': False}), Prediction(uid=377, iid=401371, r_ui=7.466643792804088, est=5.49931140596296, details={'was_impossible': False}), Prediction(uid=489, iid=9823, r_ui=3.609402240964158, est=2.6697538985324734, details={'was_impossible': False}), Prediction(uid=310, iid=346681, r_ui=8.22854855470885, est=5.3762863737269795, details={'was_impossible': False}), Prediction(uid=333, iid=1091508, r_ui=1.4965986394557826, est=5.7700069491333705, details={'was_impossible': False}), Prediction(uid=184, iid=14571, r_ui=0.19811320754716982, est=2.239584088811653, details={'was_impossible': False}), Prediction(uid=189, iid=1461201, r_ui=3.8639455782312924, est=5.212085554678118, details={'was_impossible': False}), Prediction(uid=23, iid=10949, r_ui=0.45283018867924524, est=2.620639490629134, details={'was_impossible': False})

In [325]:

def get_recommendations(user_id, model, df_interactions, df_movies, top_k=15):
    # 1. Lấy danh sách tất cả movie_id trong hệ thống
    all_movie_ids = df_movies['movie_id'].unique()
    
    # 2. Tìm các phim user này đã xem để loại bỏ
    watched_movies = df_interactions[df_interactions['user_id'] == user_id]['movie_id'].unique()
    
    # 3. Lọc ra danh sách các phim user CHƯA xem
    unseen_movies = [m_id for m_id in all_movie_ids if m_id not in watched_movies]
    
    # 4. Dự đoán điểm cho từng bộ phim chưa xem
    predictions = []
    for m_id in unseen_movies:
        # model.predict(uid, iid) trả về một object có thuộc tính 'est' là điểm dự đoán
        pred = model.predict(user_id, m_id)
        predictions.append((m_id, pred.est))
    
    # 5. Sắp xếp theo điểm dự đoán giảm dần
    predictions.sort(key=lambda x: x[1], reverse=True)
    
    # 6. Lấy Top K phim đầu bảng
    top_recommendations = predictions[:top_k]
    
    result = []
    for m_id, score in top_recommendations:
        movie_info = df_movies[df_movies['movie_id'] == m_id].iloc[0]
        result.append({
            'movie_id': m_id,
            'title': movie_info['title'],
            'genres': movie_info['genres'],
            'predicted_score': round(score, 2)
        })
        
    return pd.DataFrame(result)

user_test = 42 # Thử với user bất kỳ
recommendations = get_recommendations(user_test, algo, df_interactions, df_movies, top_k=20)
print(f"Top 20 phim gợi ý cho User {user_test}:")
print(recommendations)

Top 20 phim gợi ý cho User 42:
    movie_id                                            title  \
0      10206                         Buffy the Vampire Slayer
1     467905                            How to Make a Killing
2      10925                    The Return of the Living Dead
3       8090                                      Untraceable
4       4552                            A Tale of Two Sisters
5       2265                                             Momo
6      75983                            The Rules of the Game
7      10521                                       Bride Wars
8     194662  Birdman or (The Unexpected Virtue of Ignorance)
9      10951                                         Gorgeous
10   1302916                                       Heart Eyes
11    537971                                              Mia
12     78139             Lupin the Third: Alcatraz Connection
13     28032                                       Thumbelina
14     68727                                           Trance
15      9415                                   Murder at 1600
16    760765                                 Hula Fulla Dance
17    512195                                       Red Notice
18     51383                               Hollywood Handicap
19   1239481                               Raqqa: Spy vs. Spy

                                               genres  predicted_score
0                              Horror, Action, Comedy             7.15
1                                    Comedy, Thriller             7.03
2                     Horror, Comedy, Science Fiction             7.01
3             Drama, Horror, Thriller, Crime, Mystery             6.98
4                              Drama, Horror, Mystery             6.87
5   Fantasy, Comedy, Science Fiction, Mystery, Family             6.86
6                                               Crime             6.68
7                                     Comedy, Romance             6.67
8                                       Drama, Comedy             6.67
9                  Adventure, Action, Comedy, Romance             6.65
10                            Horror, Comedy, Romance             6.64
11                                 Drama, Documentary             6.62
12      Adventure, Animation, Comedy, Crime, TV Movie             6.61
13                Fantasy, Animation, Romance, Family             6.61
14                           Thriller, Crime, Mystery             6.59
15            Drama, Action, Thriller, Crime, Mystery             6.59
16                           Animation, Drama, Comedy             6.58
17                              Action, Comedy, Crime             6.57
18                                      Comedy, Music             6.56
19                                           Thriller             6.55

In [328]:
fav_genres, unfav_genres = get_user_genres_preferences(user_test, df_interactions, df_movies)
print(f"User {user_test} thích thể loại: {fav_genres}")
print(f"User {user_test} không thích thể loại: {unfav_genres}")

User 42 thích thể loại: ['Action', 'Thriller', 'Drama', 'Adventure', 'Comedy', 'Crime', 'Family', 'Animation', 'Horror']
User 42 không thích thể loại: ['Fantasy', 'Romance', 'Science Fiction', 'Mystery', 'War', 'History', 'Western', 'TV Movie', 'Music', 'Documentary']

In [332]:
count = 0
for row in recommendations.itertuples():
    if is_movie_relevant(row.movie_id, df_movies, fav_genres, unfav_genres):
        count += 1
print(f"Tổng số phim phù hợp với sở thích của User {user_test}: {count} / {len(recommendations)}")

Tổng số phim phù hợp với sở thích của User 42: 15 / 20